import 'dart:io';

import 'package:classic_suite/games/klondike/game_state.dart';
import 'package:classic_suite/games/klondike/solver.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test(
    'generate winnable seed corpus',
    () {
      final targetCount = int.parse(
        Platform.environment['SOLITAIRE_SEED_COUNT'] ?? '10',
      );
      final outputPath =
          Platform.environment['SOLITAIRE_SEED_OUTPUT'] ??
          '/tmp/klondike_winnable_seeds.dart';
      final maxVisitedStates = int.parse(
        Platform.environment['SOLITAIRE_SOLVER_MAX_VISITED'] ?? '150000',
      );
      final maxDepth = int.parse(
        Platform.environment['SOLITAIRE_SOLVER_MAX_DEPTH'] ?? '350',
      );

      final drawOneSeeds = _collectSeeds(
        drawCount: 1,
        targetCount: targetCount,
        maxVisitedStates: maxVisitedStates,
        maxDepth: maxDepth,
      );
      final drawThreeSeeds = _collectSeeds(
        drawCount: 3,
        targetCount: targetCount,
        maxVisitedStates: maxVisitedStates,
        maxDepth: maxDepth,
      );

      File(
        outputPath,
      ).writeAsStringSync(_renderSeedFile(drawOneSeeds, drawThreeSeeds));
    },
    timeout: const Timeout(Duration(hours: 2)),
    skip:
        'Manual corpus generation only. Use tool/generate_klondike_winnable_seeds.dart.',
  );
}

List<int> _collectSeeds({
  required int drawCount,
  required int targetCount,
  required int maxVisitedStates,
  required int maxDepth,
}) {
  final solver = KlondikeSolver(
    maxVisitedStates: maxVisitedStates,
    maxDepth: maxDepth,
  );
  final seeds = <int>[];
  var candidate = 1;
  var tested = 0;

  while (seeds.length < targetCount) {
    final state = GameState(drawCount: drawCount);
    state.dealSeededGame(candidate);
    if (solver.isSolvable(state)) {
      seeds.add(candidate);
      // ignore: avoid_print
      print(
        'draw $drawCount: accepted ${seeds.length}/$targetCount at seed $candidate after ${tested + 1} candidates',
      );
    }

    tested++;
    candidate++;
    if (tested % 500 == 0) {
      // ignore: avoid_print
      print(
        'draw $drawCount: tested $tested candidates, found ${seeds.length} seeds so far',
      );
    }
  }

  return seeds;
}

String _renderSeedFile(List<int> drawOneSeeds, List<int> drawThreeSeeds) {
  final buffer = StringBuffer()
    ..writeln('// Generated by test/_klondike_seed_generation_test.dart.')
    ..writeln('// Do not edit by hand unless regenerating the corpus.')
    ..writeln()
    ..writeln('const List<int> kWinnableDrawOneSeeds = <int>[');

  _writeSeedList(buffer, drawOneSeeds);
  buffer
    ..writeln('];')
    ..writeln()
    ..writeln('const List<int> kWinnableDrawThreeSeeds = <int>[');
  _writeSeedList(buffer, drawThreeSeeds);
  buffer.writeln('];');
  return buffer.toString();
}

void _writeSeedList(StringBuffer buffer, List<int> seeds) {
  for (int index = 0; index < seeds.length; index += 10) {
    final slice = seeds.skip(index).take(10).join(', ');
    buffer.writeln('  $slice,');
  }
}
