// Generated by test/_klondike_seed_generation_test.dart.
// Do not edit by hand unless regenerating the corpus.

const List<int> kWinnableDrawOneSeeds = <int>[
  8,
  14,
  18,
  30,
  34,
  35,
  42,
  44,
  49,
  66,
];

const List<int> kWinnableDrawThreeSeeds = <int>[
  2,
  8,
  24,
  28,
  30,
  39,
  42,
  57,
  68,
  69,
];
