import 'dart:io';

import 'package:classic_suite/games/klondike/game_state.dart';
import 'package:classic_suite/games/klondike/solver.dart';

Future<void> main(List<String> args) async {
  final config = _GeneratorConfig.parse(args);

  final drawOneSeeds = _collectSeeds(
    drawCount: 1,
    targetCount: config.targetCount,
    startSeed: config.startSeed,
    maxVisitedStates: config.maxVisitedStates,
    maxDepth: config.maxDepth,
  );
  final drawThreeSeeds = _collectSeeds(
    drawCount: 3,
    targetCount: config.targetCount,
    startSeed: config.startSeed,
    maxVisitedStates: config.maxVisitedStates,
    maxDepth: config.maxDepth,
  );

  stdout.write(_renderSeedFile(drawOneSeeds, drawThreeSeeds));
}

List<int> _collectSeeds({
  required int drawCount,
  required int targetCount,
  required int startSeed,
  required int maxVisitedStates,
  required int maxDepth,
}) {
  final solver = KlondikeSolver(
    maxVisitedStates: maxVisitedStates,
    maxDepth: maxDepth,
  );
  final seeds = <int>[];
  var candidate = startSeed;
  var tested = 0;

  while (seeds.length < targetCount) {
    final state = GameState(drawCount: drawCount);
    state.dealSeededGame(candidate);
    if (solver.isSolvable(state)) {
      seeds.add(candidate);
      stderr.writeln(
        'draw $drawCount: accepted ${seeds.length}/$targetCount at seed $candidate after ${tested + 1} candidates',
      );
    }

    tested++;
    candidate++;
    if (tested % 500 == 0) {
      stderr.writeln(
        'draw $drawCount: tested $tested candidates, found ${seeds.length} seeds so far',
      );
    }
  }

  return seeds;
}

String _renderSeedFile(List<int> drawOneSeeds, List<int> drawThreeSeeds) {
  final buffer = StringBuffer()
    ..writeln('// Generated by tool/generate_klondike_winnable_seeds.dart.')
    ..writeln('// Do not edit by hand unless regenerating the corpus.')
    ..writeln()
    ..writeln('const List<int> kWinnableDrawOneSeeds = <int>[');

  _writeSeedList(buffer, drawOneSeeds);
  buffer
    ..writeln('];')
    ..writeln()
    ..writeln('const List<int> kWinnableDrawThreeSeeds = <int>[');
  _writeSeedList(buffer, drawThreeSeeds);
  buffer.writeln('];');
  return buffer.toString();
}

void _writeSeedList(StringBuffer buffer, List<int> seeds) {
  for (int index = 0; index < seeds.length; index += 10) {
    final slice = seeds.skip(index).take(10).join(', ');
    buffer.writeln('  $slice,');
  }
}

class _GeneratorConfig {
  const _GeneratorConfig({
    required this.targetCount,
    required this.startSeed,
    required this.maxVisitedStates,
    required this.maxDepth,
  });

  final int targetCount;
  final int startSeed;
  final int maxVisitedStates;
  final int maxDepth;

  static _GeneratorConfig parse(List<String> args) {
    var targetCount = 10;
    var startSeed = 1;
    var maxVisitedStates = 150000;
    var maxDepth = 350;

    for (final arg in args) {
      if (arg.startsWith('--count=')) {
        targetCount = int.parse(arg.substring('--count='.length));
      } else if (arg.startsWith('--start=')) {
        startSeed = int.parse(arg.substring('--start='.length));
      } else if (arg.startsWith('--max-visited=')) {
        maxVisitedStates = int.parse(arg.substring('--max-visited='.length));
      } else if (arg.startsWith('--max-depth=')) {
        maxDepth = int.parse(arg.substring('--max-depth='.length));
      } else {
        throw ArgumentError('Unsupported argument: $arg');
      }
    }

    return _GeneratorConfig(
      targetCount: targetCount,
      startSeed: startSeed,
      maxVisitedStates: maxVisitedStates,
      maxDepth: maxDepth,
    );
  }
}
